services:
  - type: web
    name: expense-system
    env: php
    buildCommand: >
      composer install --no-dev --optimize-autoloader &&
      npm install &&
      npm run build &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache
    startCommand: >
      chmod -R 775 storage bootstrap/cache &&
      php artisan migrate &&
      php artisan serve --host 0.0.0.0 --port 10000
    plan: free
