services:
  app:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
    environment:
      APP_ENV: production
      APP_KEY: base64:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      APP_DEBUG: false
      APP_URL: http://localhost
      LOG_CHANNEL: stack

      DB_CONNECTION: mysql
      DB_HOST: prod-mysql-1
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: rootpass123
    volumes:
      - ../../:/var/www/html   # ←Laravelプロジェクト全体をマウント
    depends_on:
      - mysql
    networks:
      - laravel

  web:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ../../:/var/www/html
      - ../../docker/prod/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: laravel
      # MYSQL_USER: root
      # MYSQL_PASSWORD: rootpass123
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
